export default function Head() {
  return (
    <>
      <title>Pres Is The Best</title>
      <meta
        content="width=device-width, initial-scale=1"
        name="viewport"
      />
      <meta
        name="description"
        content="Generated by create next app"
      />
      <link
        rel="icon"
        href="/favicon.ico"
      />
      <link
        rel="preconnect"
        href="https://fonts.googleapis.com"
      />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
    </>
  );
}
